### ISSUE TITLE
Handle `read_loop`  failures

### ISSUE THREAD

**Issue by aesteve** [aesteve/vertx-eventbus-client-rs#1]
If the loop that reads from the TCP connection fails, the user will never been notified.

There are multiple ways to address this:
- handle automatic reconnect
- notify users of critical errors like this by letting the user attach a callback (the JS way would be an `onError`  callback)
- considering that the whole application should panic in that case and let the user deal with panics at a higher level (restart app, etc)

**Comment by adhesivee** [comment]
Another suggestion that might work is to send `Result` to the handler.
This way every handler can decide if it wants to panic or not.

**Comment by aesteve** [comment]
Hello and thanks a lot for your help.

Let me make sure I understand your suggestion correctly: 

The idea would be that instead of having `fn consumer(address: String) -> Iterator<Item=Message>`  we would have: ` fn consumer(address: String) -> Iterator<Item=Result<Message, Error>>`  where `Error` could signal different kind or Errors like an unmarshalling error for the incoming message (transient, auto-recoverable), or a "fatal" error (like TCP disconnect) where the user would have to do something.

Am I understanding correctly?

**Comment by adhesivee** [comment]
Yes that is what mean.
I think it has the benefit that there is a clear separation of expected result and unexpected result. For me at least it would be easier to understand where to look, so I won't have to browse the docs in that case. 

I don't think it will resolve all the problems. For example if it is not possble to[notify](https://github.com/aesteve/vertx-eventbus-client-rs/blob/master/src/listener.rs#L80) the handler anymore. I think using `panic` or `onError` still could be relevant.

**Comment by aesteve** [comment]
Thank you, here's a first try: https://github.com/aesteve/vertx-eventbus-client-rs/pull/5 if I understood what you mean correctly.

**Comment by adhesivee** [comment]
Yup this is what I meant

**Comment by aesteve** [comment]
Fixed in #5
